### ISSUE TITLE
Please add the rpm generation yaml file

### ISSUE THREAD

**Issue by martonmiklos** [hanhsuan/libqmlchewing-plug#1]
The project cannot be deployed after checkout because the yaml/spec file is missing:

_Fatal: No spec file found in '/home/mersdk/share//Projektek/jolla/libqmlchewing-plug/rpm/' and couldn't make one from a yaml #1_

**Comment by hanhsuan** [comment]
I also would like to have one,but I don't know how to make it yet.
I make the rpm from Sailfish OS IDE to deploy directly, cause I don't really understand how to write a spec file for. This one is more complicated than jolla-chewing.
I have refered japanese input method before, but I haven't succes yet.
If you could kindly give me some hint, it would be very nice.

**Comment by martonmiklos** [comment]
Hey,

The spec file is usually generated by the spectacle from a YAML file. 
I am working on a Presage based word prediction input plugin, and this is why I came across this project.

I will upload it to github soon and it will give you an example how they should be used.

**Comment by hanhsuan** [comment]
Thanks a lot.
The information on the Sailfish OS website is same as you said.
But when I create a plugin in the Sailfish OS IDE, there is no YAML file anywhere.
It seems that YAML file will be created in application project, but not plugin project.

**Comment by hanhsuan** [comment]
Hi 
I have made and uploaded the spec file.
If you feel ok for it, I will close this issue during this weekend.

**Comment by martonmiklos** [comment]
Hey,

I have promised you to send a yaml sample so here is it:
https://github.com/martonmiklos/sailfishos-presage-predictor/blob/master/rpm/jollapresageplugin.yaml
(the project is a similar input handler plugin just I decide to deploy the QML and the C++ plugin in the same package).

In fact the spec file is a generated result of the spectacle, so it should not tracked by git in theory.

**Comment by hanhsuan** [comment]
Hi,
I have writen almost the same content with this during these days, but that could be builded with "mb2 -t SailfishOS-armv7hl build" command.
The spec file that I upload is worked with this command by add .pro file after %qtc_qmake5.
BTW, thanks for your sample.
